CREATE TABLE `jobApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` int NOT NULL,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`cvUrl` varchar(1024),
	`coverLetter` text,
	`status` enum('new','reviewed','shortlisted','rejected','hired') NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `jobApplications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employerId` int,
	`title` varchar(256) NOT NULL,
	`company` varchar(256) NOT NULL,
	`location` varchar(256) NOT NULL,
	`salaryMin` int,
	`salaryMax` int,
	`salaryType` enum('annual','hourly','daily') DEFAULT 'annual',
	`jobType` enum('full_time','part_time','contract','temporary') NOT NULL DEFAULT 'full_time',
	`sector` varchar(128) NOT NULL,
	`sponsorshipOffered` boolean NOT NULL DEFAULT true,
	`socCode` varchar(32),
	`description` text NOT NULL,
	`requirements` text,
	`benefits` text,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(32),
	`applyUrl` varchar(1024),
	`tier` enum('free','sponsored','premium','managed') NOT NULL DEFAULT 'free',
	`status` enum('draft','pending','active','expired','closed') NOT NULL DEFAULT 'pending',
	`isFeatured` boolean NOT NULL DEFAULT false,
	`viewCount` int NOT NULL DEFAULT 0,
	`applicationCount` int NOT NULL DEFAULT 0,
	`stripePaymentId` varchar(256),
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`)
);
